# Generated by Django 2.2 on 2019-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('ans_date', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
