# Generated by Django 2.2 on 2019-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='ans_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='ner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fly',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
